### ISSUE TITLE
404 not found when trying to navigate to public directory

### ISSUE THREAD

**Issue by frankhubrepo** [utmsigep/member-directory#220]
I downloaded the project and executed composer install, it seems to have installed everything but when i try to go to localhost/member-directory/public , it auto navigates to login and i get a 404 not found error message.
![image](https://user-images.githubusercontent.com/26232103/104018161-c3146900-518f-11eb-8890-f177aeeae662.png)

**Comment by stephenyeargin** [comment]
It appears you might be attempting to use your local web server to get the application up and running. I'd advise using the [built-in Symfony web server](https://symfony.com/doc/current/setup/symfony_server.html) for evaluating (see the steps in the [Developer Quick Start](https://github.com/utmsigep/member-directory/wiki/Developer-Quick-Start)) guide. Additionally, the URLs may not behave as expected if it is not at the root of the web server.

**Comment by stephenyeargin** [comment]
Closing this off for now.
